<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charSet="utf-8"/>
      <meta name="robots" content="index, follow"/>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
      <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"/>
      <title>Usairling | Privacy Policy</title>
      <meta name="keywords" content="Usairling, cheap flight booking website, best place to book flight, online flight booking"/>
      <link rel="canonical" href="https://www.usairling.com/privacy"/>
      <meta name="description" content="Usairling.com and its related companies (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) value your trust and want you to be familiar with how we collect, use, and disclose information."/>
<meta name="format-detection" content="telephone=no"> 

<link rel="stylesheet" type="text/css" href="/resources/css/home.css">
<link rel="stylesheet" type="text/css" href="/resources/css/demo.css">
<link rel="shortcut icon" href="/resources/images/favicon.ico" type="image/x-icon">
    <link href="/resources/css/cms6003.css?v=0131191753" rel="stylesheet" type="text/css" />
  
</head>
<body class="cms-page no-midbar">
   
	<!--HEADER START-->
<jsp:include page="header.jsp" />

<!--HEADER END-->

		<div id="main-wrapper" role="main">
            <!--SITE NAVIGATION PATH START -->
         <div class="page-title page-title--small align-left">
            <div class="container">
               <div class="page-title__content">
                  <h1 class="page-title__name">Privacy Policy</h1>
               </div>
            </div>
            <div class="breadcrumb_area full-w text-uppercase none" style="background-image:">
               <div class="container">
                  <ul class="bradcum">
                     <li> <a href="/">Home</a> </li>
                     <li class="breadcrumb-item active" aria-current="page"> Privacy</li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="about-uspage privacy__policy full-w pyblock-80 mb-5">
            <div class="container">
               <div class="row">
                  <div class="about-font-18 col-xl-12 col-12">
                     <h2 class="sub-title">Privacy policy</h2>
                     <p>Usairling.com and its related companies (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) value your trust and want you to be familiar with how we collect, use, and disclose information. This Privacy Policy describes our practices in connection with information that we collect through the websites or mobile websites (the &quot;Websites&quot;), and our other online services, in all cases, from which you access this Privacy Policy (collectively, including the Websites and the &quot;Services&quot;). By providing Personal Information to us, you agree to the terms and conditions of this Privacy Policy.</p>
                     <h2>PERSONAL INFORMATION</h2>
                     <p>Personal Information We May Collect &quot;Personal Information&quot; is information that identifies you as an individual or relates to an identifiable person, including, for example:</p>
                     <p>Name Postal address(es) Telephone number Email address Credit and debit card number and related information Social media account ID Passport number Number assigned by a transportation agency, such as a Transportation Security Administration known traveler number Any other information you provide when you communicate or book travel with us (e.g., your dietary and other preferences or needs), as well as information about your bookings (e.g., points of departure and destinations) If you submit any Personal Information relating to other people to us or to our service providers in connection with the Services, you represent that you have the authority to do so and to permit us to use the information in accordance with this Privacy Policy.</p>
                     <h2>HOW WE MAY COLLECT PERSONAL INFORMATION</h2>
                     <p>We and our service providers may collect Personal Information in a variety of ways, including:</p>
                     <p>Through the Services: We may collect Personal Information through the Services, such as when you make a booking or register for a promotion.</p>
                     <p>Offline: We may collect Personal Information from you offline, such as when you contact customer service. From Other Sources: We may receive your Personal Information from other sources, such as public databases, joint marketing partners, social media platforms (including from people with whom you are friends or otherwise connected), and other third parties, to the extent permitted by applicable law. How We May Use Personal Information</p>
                     <h2>WE MAY USE PERSONAL INFORMATION</h2>
                     <p>To complete and fulfill your booking or purchase, which includes processing your payment, communicate with you regarding your booking or purchase, and provide you with related customer service. We use passport information for the purpose of travel bookings</p>
                     <p>To respond to your inquiries and fulfill your requests, such as to send you newsletters. To send administrative information to you, such as information regarding the Services and changes to our terms, conditions, and policies</p>
                     <p>To send you marketing communications that we believe may be of interest to you, to the extent permitted by law. To personalize your experience on the Services by presenting products and offers tailored to you. To allow you to participate in sweepstakes, contests, and similar promotions and to administer these activities. Some of these activities have additional rules, which may contain additional information about how we use and disclose your Personal Information. We suggest that you read any such rules carefully, as you will be bound by them if you choose to participate. To facilitate social sharing functionalit</p>
                     <p>To allow you to send messages to another person through the Services. By using this functionality, you are telling us that you are entitled to provide us with your friend&#x27;s name and email address.</p>
                     <p>For our business purposes, such as data analysis, audits, fraud monitoring and prevention, developing new products, enhancing, improving, or modifying our Services, identifying usage trends, determining the effectiveness of our promotional campaigns, and operating and expanding our business activitie</p>
                     <p>As we believe to be necessary or appropriate: (a) under applicable law, including laws outside your state or country of residence; (b) to comply with legal process and to prevent, detect, or suppress abuse, fraud, or criminal activity; (c) to respond to requests from public and government authorities and self-regulatory organizations, including public and government authorities and self-regulatory organizations outside your state or country of residence; (d) to enforce our terms and conditions; (e) to protect our operations, assets, or interests or those of any of our affiliates; (f) to protect our rights, privacy, safety, or property, and/or that of our affiliates, you, or others; and (g) to allow us to pursue available remedies or limit the damages that we may sustain</p>
                     <h2>HOW PERSONAL INFORMATION MAY BE DISCLOSED</h2>
                     <p>Your Personal Information may be disclosed or transferred to the following entities. With the exception of our corporate affiliates and service providers, these entities are not controlled by us and Personal Information disclosed to them is subject to the applicable entity&#x27;s privacy policy and security practices. Therefore, we encourage you to review the privacy policies of any entity whose products or services you purchase using the Services</p>
                     <p>To our corporate affiliates worldwide for the purposes described in this Privacy Policy. Usairling. is responsible for the management of the jointly-used Personal Information. To our third party travel-related suppliers, such as airlines, hotels, and car rental companies, so that they may provide the products and services that you book or purchase using the Services. To other travel-related companies with whom we partner to provide a portion of the Services, such as airline consolidators or aggregators, other travel agencies providing access to their travel-related inventory via the Services, and travel insurance providers.</p>
                     <p>To our business partners, whose products or services may be offered on the Services, who referred you to the Services from another website or online service, or to whose website or online service the Services link. We encourage you to review the privacy policy of each such website or online service. To our third party service providers who provide services such as website hosting, data analysis, payment processing, order fulfillment, information technology and related infrastructure provision, customer service, email delivery, auditing, and other services. The information we provide to third parties service providers is subject to confidentiality obligations and is intended to be used solely for the purpose(s) permitted thereby</p>
                     <h2>TO THIRD-PARTY SPONSORS OR OPERATORS OF SURVEYS, SWEEPSTAKES, CONTESTS, AND SIMILAR PROMOTIONS</h2>
                     <p>To identify you to anyone to whom you send messages through the Services. You may also choose to disclose your Personal Information on message boards, chat, profile pages, blogs, and other services to which you are able to post information and materials. Please note that any information you post or disclose through these services will become public and may be available to other users and the general public. We urge you to be very careful when deciding to disclose any information on the Services. Subject to your social media account settings, to your friends associated with your social media account, to other website users, and to your social media account provider, in connection with your social sharing activity, such as if you connect your social media account to your Services account or log into your Services account from your social media account. By connecting your Services account and your social media account, you authorize us to share information with your social media account provider, and you understand that the use of the information we share will be governed by the social media site&#x27;s privacy policy. If you do not want your Personal Information shared with other users or with your social media account provider, please do not connect your social media account with your Services account, and do not participate in social sharing on the Services. To a third party, in the event of any reorganization, merger, sale, joint venture, assignment, transfer, or other disposition of all or any portion of our business, assets, or stock (including in connection with any bankruptcy or similar proceedings). As we believe to be necessary or appropriate: (a) under applicable law, including laws outside your state or country of residence; (b) to comply with legal process and to prevent, detect, or suppress abuse, fraud, or criminal activity; (c) to respond to requests from public and government authorities and self-regulatory organizations, including public and government authorities and self-regulatory organizations outside your state or country of residence; (d) to enforce our terms and conditions; (e) to protect our operations, assets, or interests or those of any of our affiliates; (f) to protect our rights, privacy, safety, or property, and/or that of our affiliates, you, or others; and (g) to allow us to pursue available remedies or limit the damages that we may sustain.</p>
                     <h2>OTHER INFORMATION</h2>
                     <p>Other Information We May Collect &quot;Other Information&quot; is any information that does not directly reveal your specific identity or does not directly relate to an individual. If we are required to treat Other Information as Personal Information under applicable law, then we may use it only for the purposes for which we use and disclose Personal Information as detailed in this Privacy Policy.</p>
                     <h2>OTHER INFORMATION MAY, FOR EXAMPLE, BE</h2>
                     <p>Browser and device information App usage data Information collected through cookies, pixel tags, and other technologies Demographic information and other information provided by you Aggregated information</p>
                     <h2>HOW WE MAY COLLECT OTHER INFORMATION</h2>
                     <p>We and our third party service providers may collect Other Information in a variety of ways, including: Through your browser or device: Certain information is collected by most browsers or automatically through your device, such as your Media Access Control (MAC) address, computer type (Windows or Macintosh), screen resolution, operating system name and version, device manufacturer and model, language, Internet browser type and version, and the name and version of the Services (such as the App) you are using. We use this information to ensure that the Services function properly.</p>
                     <p>Using cookies: Cookies are pieces of information stored directly on the computer that you are using. Cookies allow us to collect information such as browser type, time spent on the Services, pages visited, language preferences, and other anonymous traffic data. We and our service providers use the information for security purposes, to facilitate navigation, to display information more effectively, to personalize your experience while using the Services, and to recognize your computer in order to assist your use of the Services. We also gather statistical information about use of the Services in order to continually improve their design and functionality, understand how they are used, and assist us with resolving questions regarding them. Cookies further allow us to select which of our advertisements or offers are most likely to appeal to you and display them while you are on the Services. We may also use cookies or other technologies to track responses to our online advertisements and to understand what site or advertisement brought you to our site. At this time, we do not respond to browser do-not-track signals.</p>
                     <p>If you do not want information collected through the use of cookies, there is a simple procedure in most browsers that allows you to automatically decline cookies or be given the choice of declining or accepting the transfer to your computer of a particular cookie (or cookies) from a particular site. </p>
                     <p> Using pixel tags and other similar technologies: Pixel tags (also known as web beacons and clear GIFs) may be used in connection with some Services to, among other things, track the actions of users of the Services (including email recipients), measure the success of our marketing campaigns, and compile statistics about usage of the Services and response rates. Analytics: We use Google Analytics, which uses cookies and similar technologies to collect and analyze information about use of the Services and report on activities and trends. This service may also collect information regarding the use of other websites, apps and online resources. You can learn about Googl </p>
                     <p>ractices by going to www.google.com/policies/privacy/?partners/, and opt out of them by downloading the Google Analytics opt-out browser add-on, available at https://tools.google.com/dlpage/gaoptout. Using Adobe Flash technology (including Flash Local Shared Objects (&quot;Flash LSOs&quot;)) and other similar technologies: We may use Flash LSOs and other technologies to, among other things, collect and store information about your use of the Services. If you do not want Flash LSOs stored on your computer, you can adjust the settings of your Flash player to block Flash LSO storage using the tools contained in the Website Storage Settings Panel. You can also control Flash LSOs by going to the Global Storage Settings Panel and following the instructions (which may include instructions that explain, for example, how to delete existing Flash LSOs (referred to as &quot;information&quot; on the Macromedia site), how to prevent Flash LSOs from being placed on your computer without your being asked, and (for Flash Player 8 and later) how to block Flash LSOs that are not being delivered by the operator of the page you are on at the time). Please note that setting the Flash Player to restrict or limit acceptance of Flash LSOs may reduce or impede the functionality of some Flash applications, including those used in connection with the Services. IP Address: Your IP address is a number that is automatically assigned to the computer that you are using by your Internet Service Provider. An IP address may be identified and logged automatically in our server log files whenever a user accesses the Services, along with the time of the visit and the page(s) that were visited. Collecting IP addresses is standard practice and is done automatically by many websites, applications and other services. We use IP addresses for purposes such as calculating usage levels, diagnosing server problems, and administering the Services. We may also derive your approximate location from your IP address.</p>
                     <p>Physical Location: We may collect the physical location of your device by, for example, using satellite, cell phone tower, or WiFi signals. We may use your device&#x27;s physical location to provide you with personalized location-based services and content. We may also share your device&#x27;s physical location with our marketing partners, to enable them to provide you with geo-targeted advertising. You may be permitted to allow or deny such uses and/or sharing of your device&#x27;s location, such as through your device settings. If you do, we and/or our marketing partners may not be able to provide you with the applicable personalized services and content.</p>
                     <p>From you: Information such as your preferred means of communication and special travel requests (for example, in connection with a disability or dietary restriction) is collected when you voluntarily provide it.</p>
                     <p>By aggregating information: Aggregated Personal Information does not personally identify you or any other user of the Services (for example, we may aggregate Personal Information to calculate the percentage of our users who have a particular telephone area code).</p>
                     <h2>HOW WE MAY USE AND DISCLOSE OTHER INFORMATION</h2>
                     <p>We may use and disclose Other Information for any purpose (except where we are required to do otherwise under applicable law), if it doesn&#x27;t qualify as Personal Information under applicable law. In some instances, we may combine Other Information with Personal Information (such as combining your name with your location). If we do, we will treat the combined information as Personal Information as long as it is combined.</p>
                     <h2>THIRD PARTY SERVICES</h2>
                     <p>This Privacy Policy does not address, and we are not responsible for, the privacy, information, or other practices of any third parties, including any third party supplier or intermediary, any third party operating any site or service to which the Services link or any third party that includes a widget on the Services (for example, the Facebook Like button or share buttons). The inclusion of a link on the Services does not imply endorsement of the linked site or service by us or by our affiliates.</p>
                     <p>In addition, we are not responsible for the information collection, use, disclosure, or security policies or practices of other organizations, such as Facebook, Apple, Google, Microsoft, or any other app developer, app provider, social media platform provider, operating system provider, wireless service provider, or device manufacturer, including with respect to any Personal Information you disclose to other organizations through or in connection with the Apps.</p>
                     <h2>THIRD PARTY ADVERTISERS</h2>
                     <p>We may use third-party advertising companies to serve advertisements regarding goods and services that may be of interest to you when you access and use the Services and other websites, apps or online services, based on information relating to your access to and use of the Services and other websites, apps or online services on any of your devices. To do so, these companies may place or recognize a unique cookie on your browser (including through use of pixel tags). They may also use these technologies and other information that they and we collect about your online use to recognize you across the devices you use, such as a mobile phone and a laptop. If you would like more information about this practice, and to learn about your choices in connection with it in desktop and mobile browsers on the particular device on which you are accessing this Privacy Policy, please visit http://www.networkadvertising.org/managing/opt_out.aspand http://www.aboutads.info/choices. You may download the AppChoices app at www.aboutads.info/appchoices to opt out in mobile apps.</p>
                     <h2>SECURITY</h2>
                     <p>We seek to use reasonable organizational, technical, and administrative measures to protect Personal Information within our organization. Unfortunately, no data transmission or storage system can be guaranteed to be 100% secure. If you have reason to believe that your interaction with us is no longer secure (for example, if you feel that the security of your account has been compromised), please immediately notify us in accordance with the &quot;Contacting Us&quot; section below.</p>
                     <h2>CHOICES AND ACCESS</h2>
                     <p>Your choices regarding our use of your Personal Information You may opt out from receiving marketing-related emails from us on a going-forward basis by following the instructions contained in each such email or by contacting us in accordance with the &quot;Contacting Us&quot; section below. You may opt out of receiving push notifications from us through your device settings.</p>
                     <p>We will try to comply with your request as soon as reasonably practicable. Please note that if you opt out of receiving marketing-related emails from us, we may still send you important administrative messages, from which you cannot opt out</p>
                     <h2>HOW YOU CAN ACCESS, CHANGE OR SUPPRESS YOUR PERSONAL INFORMATION</h2>
                     <p>If you would like to review, correct, update, suppress, or delete Personal Information that you have previously provided to us, you may contact us in accordance with the &quot;Contacting Us&quot; section below. In your request, please make clear what Personal Information you would like to have changed, whether you would like to have your Personal Information suppressed from our database, or otherwise let us know what limitations you would like to put on our use of your Personal Information. For your protection, we may only implement requests with respect to the Personal Information associated with the particular email address that you use to send us your request, and we may need to verify your identity before implementing your request. We will try to comply with your request as soon as reasonably practicable. </p>
                     <p>Please note that we may need to retain certain information for recordkeeping purposes and/or to complete any transactions that you began prior to requesting a change or deletion. There may also be residual information that will remain within our databases and other records, which will not be removed.</p>
                     <h2>YOUR CALIFORNIA AND CANADIAN PRIVACY RIGHTS</h2>
                     <p>If you are a resident of California or Canada, you may request information regarding the disclosure of your Personal Information to our affiliates and to third parties for the recipients&#x27; own direct marketing purposes. To make such a request, please contact us in accordance with the &quot;Contacting Us&quot; section below.</p>
                     <h2>RETENTION PERIOD</h2>
                     <p>We will retain your Personal Information for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted by law.</p>
                     <h2>USE OF THE SERVICES BY MINORS</h2>
                     <p>The Services are not directed to individuals under the age of eighteen (18), and we request that they not provide Personal Information through the Services.</p>
                     <h2>CROSS-BORDER TRANSFER</h2>
                     <p>Your Personal Information may be transferred, stored, accessed, and processed in any country where we have facilities or in which we engage service providers, and by using the Services you consent to the transfer of information to countries outside of your country of residence, including the United States, which may have data protection rules that are different from those of your country.</p>
                     <h2>SENSITIVE INFORMATION</h2>
                     <p>We ask that you not send us, and you not disclose, any sensitive Personal Information (e.g., Social Security numbers, information related to racial or ethnic origin, political opinions, religion or other beliefs, health, biometrics or genetic characteristics, criminal background, or trade union membership) on or through the Services or otherwise to us.</p>
                     <h2>UPDATES TO THIS PRIVACY POLICY</h2>
                     <p>We may change this Privacy Policy. The &quot;Last Updated&quot; legend at the top of this page indicates when this Privacy Policy was last revised. Any changes will become effective when we post the revised Privacy Policy on the Services. Your use of the Services following these changes means that you accept the revised Privacy Policy.</p>
                     <h2>CONTACTING US</h2>
                     <p>If you have any questions about this Privacy Policy, please contact us via email at info@usairling.com. Because email communications are not always secure, please do not include credit card or other sensitive information in your emails to us.</p>
                     <p>By using this Site, you acknowledge that the rates offered by Usairling and affiliate companies are a result of negotiation between Usairling and the Travel Suppliers and include certain fees retained by them for their services, taxes and other charges. When booking with any Travel Supplier through this Site, you authorize Usairling and affiliate companies to book reservations or enter a contract on your behalf with Travel Suppliers for the total price displayed, including such fees and any applicable taxes or charges related to the Travel Supplier&#x27;s or Cheapoflightticket &#x27;s services.</p>
                     <p>Usairling shall not be liable for errors or inaccuracies on the Site, or the failure of Travel Suppliers from whom you obtain services through this Site, including but not limited to airlines, tour operators, suppliers and consolidators. Usairling , in providing travel management services, does not endorse, guarantee or insure the products or services which are provided by an external supplier, the financial position of such suppliers or the reimbursement to you from any loss as a result of the financial condition of such supplier. In the event that a supplier defaults prior to providing the service to you where a payment has been made, your sole recourse for a refund shall be the defaulting supplier, or from other responsible third party unless such loss was caused solely by Usairling. In those situations in which a supplier defaults prior to providing services you may pursue any recourse against the supplier for a refund, as permitted by law or statute.</p>
                     <p>Except as expressly stated herein, Usairling assumes no responsibility for actions relating to travel services beyond the control of Usairling or its employees. Usairling is not responsible or liable for any act, error, omission, injury, loss, accident, damage, delay, nonperformance, irregularity, or any consequence thereof, which may be occasioned through neglect, or default or any other act or inaction of any Travel Supplier. Usairling shall not be liable for any fluctuation in price or change in schedule or equipment or accommodations for any travel service, which occurs subsequent to booking and payment for such service. Usairling shall not be liable for any cancellation, overbooking, delay, re-routing, strike, any weather occurrence or governmental occurrence as it affects your travel reservation made with us. Usairling shall not be liable for the depiction of travel products and services made available by any supplier of travel products and services, including but not limited to photographs, listed amenities, ratings, and discounts</p>
                     <p>Usairling acts as a service that provides value added service to retail travel agents and consumers. Usairling has no control over and assumes no liability for the actions of the suppliers from whom it obtains travel products or services</p>
                     <p>Usairling shall not be liable for final currency conversion or rates when paid after a travel reservation is made with us for international travel products and services. You agree and acknowledge that currency rates vary and any quoted price on the Site in local currency is a guideline, and not binding on us or the Travel Supplier.</p>
                     <p>Once certain travel reservations are made and paid for they may be completely non-refundable or there may be a penalty involved in cancellation or seeking a refund from the supplier of travel products and services. Once tickets have been issued there may be a penalty involved for cancellations and refunds. We do not have control over printed prices on the tickets, although some tickets may have BT (bulk fare) printed on them, some may have a specific value on them, which may be different (lower or higher) than the fare collected.</p>
                     <p>Discounts offered may vary depending on a number of factors including airlines utilized, class of service, destination, time of year (low, mid or high season), advance notice provided, minimum stay requirements fulfilled and flight load.</p>
                     <p>Usairling does not guarantee, endorse, validate or promote other advertiser&#x27;s products and services that are advertised on our Site.</p>
                     <p>By booking with us a contract may be formed between you and a Travel Supplier, and additional Terms &amp; Conditions may apply to your booking and purchase of travel-related goods and services. Please read the additional Terms &amp; Conditions provided by such Travel Supplier carefully. You hereby agree to be bound by all the Terms &amp; Conditions of purchase imposed by any Travel Supplier with whom you choose to contract, including, but not limited to, payment of all amounts when due and compliance with the Travel Supplier&#x27;s rules and restrictions regarding availability and use of fares, products, or services. Some Travel Suppliers may require you to present a credit card or cash deposit upon check-in to cover additional expenses incurred during the use of the reserved products or services. Such deposit is unrelated to any payment received by Usairling for your airline ticket booking. You understand that any violation of a Travel Supplier&#x27;s rules and restrictions may result in the cancellation of your reservation(s), in denial of access to the respective Service Element or services, in your forfeiting any amount paid for such reservation(s), and/or in our debiting your account for any costs we incur as a result of such violation.</p>
                     <h3>DISPUTES</h3>
                     <p>Usairling is committed to customer satisfaction, so if you have a problem or dispute, we will try to resolve your concerns You agree to give us an opportunity to resolve any disputes or claims relating in any way to the Website, any dealings with our customer service agents, any services or products provided, any representations made by us, or our Privacy Policy (&quot;Claims&quot;) by contacting Customer Support.</p>
                     <h3>PROHIBITED ACTIVITIES</h3>
                     <p>The content and information on Usairling (including, but not limited to, price and availability of travel services), as well as the infrastructure used to provide such content and information, are proprietary to us or our suppliers and providers. While you may make limited copies of your travel itinerary (and related documents) for travel or service reservations booked through Usairling, you agree not to otherwise modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell or re-sell any information, software, products, or services obtained from or through Usairling. Additionally, you agree not to:</p>
                     <ul>
                        <li> Use Usairling or its contents for any commercial purpose;</li>
                        <li> Make any speculative, false, or fraudulent reservation or any reservation in anticipation of demand;</li>
                        <li>3. Access, monitor or copy any content or information of Usairling using any robot, spider, scraper or other automated means or any manual process for any purpose without our express written permission;</li>
                        <li>4. Violate the restrictions in any robot exclusion headers on Usairling or bypass or circumvent other measures employed to prevent or limit access to Usairling;</li>
                        <li>Take any action that imposes, or may impose, in our discretion, an unreasonable or disproportionately large load on our infrastructure;</li>
                        <li> Deep-link to any portion of Usairling (including, without limitation, the purchase path for any travel services) for any purpose without our express written permission.</li>
                        <li> &quot;Frame&quot;, &quot;mirror&quot; or otherwise incorporate any part of Usairling into any other website without our prior written authorization</li>
                     </ul>
                     <p>If your booking or account shows signs of fraud, abuse or suspicious activity, we may cancel any travel or service reservations associated with your name, email address or account. In addition, we may verify (i.e. preauthorize) your credit card. If you have conducted any fraudulent activity, Usairling reserves the right to take any necessary legal action and you may be liable for monetary losses to Usairling, including litigation costs and damages.</p>
                  </div>
               </div>
            </div>
         </div>
		</div>

<script src="/resources/scripts/jquery-1.11.1.min.js"></script>
<jsp:include page="footer.jsp" />


<!--FOOTER END -->

</body>
</html>